UkrainiansId/UkrainiansId.Web/Models/ErrorViewModel.cs
using System;

namespace UkrainiansId.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UkrainiansId/UkrainiansId.Web/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace UkrainiansId.Web.Models
{
    public class LoginViewModel
    {
        [Required, MinLength(7), MaxLength(100)]
        public string Login { get; set; }
        [Required, MinLength(8), MaxLength(35)]
        public string Password { get; set; }
    }
}

UkrainiansId/UkrainiansId.Web/Models/TestUser.cs
namespace UkrainiansId.Web.Models
{
    public class TestUser
    {
        public string Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
    }
}

UkrainiansId/UkrainiansId.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using System.Linq;
using UkrainiansId.Web.Models;

namespace UkrainiansId.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        [HttpGet("Privacy")]
        public IActionResult Privacy()
        {
            return View();
        }

        [Authorize]
        [HttpGet("Private")]
        public IActionResult Private()
        {
            return View(User.Claims.ToList());
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

UkrainiansId/UkrainiansId.Web/Controllers/IdentityController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using UkrainiansId.Web.Models;

namespace UkrainiansId.Web.Controllers
{
    [AllowAnonymous, Route("identity")]
    public class IdentityController : Controller
    {
        private readonly IAuthenticationSchemeProvider _schemeProvider;
        public IdentityController(IAuthenticationSchemeProvider schemeProvider)
        {
            _schemeProvider = schemeProvider;
        }

        [HttpGet("login")]
        public async Task<IActionResult> Login()
        {
            if (User.Identity.IsAuthenticated)
                return LocalRedirect("~/");
            ViewBag.Providers = (await _schemeProvider.GetAllSchemesAsync()).Where(x=> !string.IsNullOrEmpty(x.DisplayName)).OrderBy(x=>x.DisplayName).ToList();
            return View();
        }

        [HttpGet("logout")]
        public async Task<IActionResult> Logout()
        {
            if (User.Identity.IsAuthenticated)
                await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return LocalRedirect("/");
        }

        public IActionResult SignIn(string provider)
        {
            if (User.Identity.IsAuthenticated)
                return LocalRedirect("~/");
            return Challenge(new AuthenticationProperties { RedirectUri = Url.Action("SignInResponse") }, provider);
        }

        [HttpGet("SignInResponse")]
        public async Task<IActionResult> SignInResponse()
        {
            var result = await HttpContext.AuthenticateAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            var claims = result.Principal.Claims;
            return LocalRedirect("/");
        }

        [NonAction]
        private TestUser GetUser(IEnumerable<Claim> claims)
        {
            return new TestUser
            {
                Id = claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value,
                Email = claims.FirstOrDefault(x => x.Type == ClaimTypes.Email).Value,
                FullName = claims.FirstOrDefault(x => x.Type == ClaimTypes.Name).Value,
                Firstname = claims.FirstOrDefault(x => x.Type == ClaimTypes.GivenName).Value,
                Lastname = claims.FirstOrDefault(x => x.Type == ClaimTypes.Surname).Value,
            };
        }
    }
}

UkrainiansId/UkrainiansId.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

UkrainiansId/UkrainiansId.Web/Views/Home/Private.cshtml
@model List<System.Security.Claims.Claim>
@{
    ViewData["Title"] = "Private";
}

<h1>Private</h1>

@foreach(var claim in Model)
{
    <div>@claim.Type - @claim.Value</div>
}

UkrainiansId/UkrainiansId.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UkrainiansId.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @if (User.Identity.IsAuthenticated)
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@User.Identity.Name</a>
                }
                else
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UkrainiansId</a>
                }
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="Private">Claims</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Identity" asp-action="Logout">Log out</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - UkrainiansId.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>